name: Tiffinity
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  photo_view: ^0.15.0
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  slide_to_act: ^2.0.1
  confetti: ^0.7.0
  url_launcher: ^6.2.2
  pull_to_refresh: ^2.0.0
  timeago: ^3.6.0
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^6.0.0

  # KEEP for local notifications display
  flutter_local_notifications: ^18.0.1

  # ADD for device token generation
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: assets/images/app_icon.png
  android: true
  ios: true
  adaptive_icon_foreground: assets/images/app_icon.png
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - .env
